// package: cs3.rpc.v1beta1
// file: cs3/rpc/v1beta1/code.proto

import * as jspb from 'google-protobuf';

export enum Code {
  CODE_INVALID = 0,
  CODE_OK = 1,
  CODE_CANCELLED = 2,
  CODE_UNKNOWN = 3,
  CODE_INVALID_ARGUMENT = 4,
  CODE_DEADLINE_EXCEEDED = 5,
  CODE_NOT_FOUND = 6,
  CODE_ALREADY_EXISTS = 7,
  CODE_PERMISSION_DENIED = 8,
  CODE_UNAUTHENTICATED = 9,
  CODE_RESOURCE_EXHAUSTED = 10,
  CODE_FAILED_PRECONDITION = 11,
  CODE_ABORTED = 12,
  CODE_OUT_OF_RANGE = 13,
  CODE_UNIMPLEMENTED = 14,
  CODE_INTERNAL = 15,
  CODE_UNAVAILABLE = 16,
  CODE_DATA_LOSS = 17,
  CODE_REDIRECTION = 18,
  CODE_INSUFFICIENT_STORAGE = 19,
}

