// source: cs3/auth/applications/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var cs3_auth_provider_v1beta1_resources_pb = require('../../../../cs3/auth/provider/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_auth_provider_v1beta1_resources_pb);
var cs3_identity_user_v1beta1_resources_pb = require('../../../../cs3/identity/user/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_identity_user_v1beta1_resources_pb);
var cs3_types_v1beta1_types_pb = require('../../../../cs3/types/v1beta1/types_pb.js');
goog.object.extend(proto, cs3_types_v1beta1_types_pb);
goog.exportSymbol('proto.cs3.auth.applications.v1beta1.AppPassword', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.auth.applications.v1beta1.AppPassword = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.auth.applications.v1beta1.AppPassword, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.auth.applications.v1beta1.AppPassword.displayName = 'proto.cs3.auth.applications.v1beta1.AppPassword';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.auth.applications.v1beta1.AppPassword.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.auth.applications.v1beta1.AppPassword} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.auth.applications.v1beta1.AppPassword.toObject = function(includeInstance, msg) {
  var f, obj = {
    password: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tokenScopeMap: (f = msg.getTokenScopeMap()) ? f.toObject(includeInstance, proto.cs3.auth.provider.v1beta1.Scope.toObject) : [],
    label: jspb.Message.getFieldWithDefault(msg, 3, ""),
    user: (f = msg.getUser()) && cs3_identity_user_v1beta1_resources_pb.UserId.toObject(includeInstance, f),
    expiration: (f = msg.getExpiration()) && cs3_types_v1beta1_types_pb.Timestamp.toObject(includeInstance, f),
    ctime: (f = msg.getCtime()) && cs3_types_v1beta1_types_pb.Timestamp.toObject(includeInstance, f),
    utime: (f = msg.getUtime()) && cs3_types_v1beta1_types_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.auth.applications.v1beta1.AppPassword;
  return proto.cs3.auth.applications.v1beta1.AppPassword.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.auth.applications.v1beta1.AppPassword} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 2:
      var value = msg.getTokenScopeMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.cs3.auth.provider.v1beta1.Scope.deserializeBinaryFromReader, "", new proto.cs3.auth.provider.v1beta1.Scope());
         });
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabel(value);
      break;
    case 4:
      var value = new cs3_identity_user_v1beta1_resources_pb.UserId;
      reader.readMessage(value,cs3_identity_user_v1beta1_resources_pb.UserId.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 5:
      var value = new cs3_types_v1beta1_types_pb.Timestamp;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpiration(value);
      break;
    case 6:
      var value = new cs3_types_v1beta1_types_pb.Timestamp;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCtime(value);
      break;
    case 7:
      var value = new cs3_types_v1beta1_types_pb.Timestamp;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.auth.applications.v1beta1.AppPassword.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.auth.applications.v1beta1.AppPassword} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.auth.applications.v1beta1.AppPassword.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTokenScopeMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.cs3.auth.provider.v1beta1.Scope.serializeBinaryToWriter);
  }
  f = message.getLabel();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      cs3_identity_user_v1beta1_resources_pb.UserId.serializeBinaryToWriter
    );
  }
  f = message.getExpiration();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      cs3_types_v1beta1_types_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCtime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      cs3_types_v1beta1_types_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUtime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      cs3_types_v1beta1_types_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string password = 1;
 * @return {string}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, cs3.auth.provider.v1beta1.Scope> token_scope = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.cs3.auth.provider.v1beta1.Scope>}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getTokenScopeMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.cs3.auth.provider.v1beta1.Scope>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.cs3.auth.provider.v1beta1.Scope));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.clearTokenScopeMap = function() {
  this.getTokenScopeMap().clear();
  return this;};


/**
 * optional string label = 3;
 * @return {string}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional cs3.identity.user.v1beta1.UserId user = 4;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getUser = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, cs3_identity_user_v1beta1_resources_pb.UserId, 4));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
*/
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.hasUser = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional cs3.types.v1beta1.Timestamp expiration = 5;
 * @return {?proto.cs3.types.v1beta1.Timestamp}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getExpiration = function() {
  return /** @type{?proto.cs3.types.v1beta1.Timestamp} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Timestamp, 5));
};


/**
 * @param {?proto.cs3.types.v1beta1.Timestamp|undefined} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
*/
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setExpiration = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.clearExpiration = function() {
  return this.setExpiration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.hasExpiration = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional cs3.types.v1beta1.Timestamp ctime = 6;
 * @return {?proto.cs3.types.v1beta1.Timestamp}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getCtime = function() {
  return /** @type{?proto.cs3.types.v1beta1.Timestamp} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Timestamp, 6));
};


/**
 * @param {?proto.cs3.types.v1beta1.Timestamp|undefined} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
*/
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setCtime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.clearCtime = function() {
  return this.setCtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.hasCtime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional cs3.types.v1beta1.Timestamp utime = 7;
 * @return {?proto.cs3.types.v1beta1.Timestamp}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.getUtime = function() {
  return /** @type{?proto.cs3.types.v1beta1.Timestamp} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Timestamp, 7));
};


/**
 * @param {?proto.cs3.types.v1beta1.Timestamp|undefined} value
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
*/
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.setUtime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.auth.applications.v1beta1.AppPassword} returns this
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.clearUtime = function() {
  return this.setUtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.auth.applications.v1beta1.AppPassword.prototype.hasUtime = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.cs3.auth.applications.v1beta1);
